# Generated by Django 3.0.6 on 2020-06-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0002_auto_20200609_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment_list',
            name='visit_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
